import { useState } from 'react';
import { Bell, BarChart3, Building2, CalendarDays, ChevronDown, Clapperboard, FileText, Film, Gauge, Home, Menu, Package, Receipt, Settings, Tag, Ticket, UserRound, Users, X } from 'lucide-react';

const nav = [{ name: 'Tổng quan', icon: Home }, { name: 'Phim', icon: Film, children: ['Danh sách phim', 'Thêm phim mới', 'Phim đang chiếu'] }, { name: 'Suất chiếu', icon: CalendarDays, children: ['Lịch suất chiếu', 'Tạo suất chiếu', 'Khóa suất chiếu'] }, { name: 'Rạp & Phòng chiếu', icon: Building2, children: ['Danh sách phòng', 'Sơ đồ ghế', 'Trạng thái thiết bị'] }, { name: 'Loại vé & Giá vé', icon: Tag, children: ['Danh sách loại vé', 'Thiết lập giá vé', 'Giá theo khung giờ'] }, { name: 'Hàng hóa', icon: Package, children: ['Danh mục hàng hóa', 'Tồn kho', 'Nhập xuất kho'] }, { name: 'Voucher / Khuyến mãi', icon: Ticket, children: ['Danh sách voucher', 'Tạo voucher', 'Lịch sử sử dụng'] }, { name: 'Khách hàng', icon: UserRound, children: ['Danh sách khách hàng', 'Thành viên', 'Lịch sử giao dịch'] }, { name: 'Nhân viên', icon: Users, children: ['Tài khoản nhân viên', 'Phân quyền', 'Ca làm việc'] }, { name: 'Giao dịch', icon: Receipt, children: ['Danh sách giao dịch', 'Tra cứu giao dịch', 'Yêu cầu hoàn tiền'] }, { name: 'Báo cáo', icon: BarChart3, children: ['Doanh thu', 'Hiệu suất suất chiếu', 'Đối soát dữ liệu'] }, { name: 'Cài đặt hệ thống', icon: Settings }] as const;
const movieData = [['Lật Mặt 7: Một Điều Ước', '18.250.000 đ', '128 suất chiếu', 'poster-one'], ['Doraemon: Nobita Và Cuộc Phiêu Lưu', '9.850.000 đ', '96 suất chiếu', 'poster-two'], ['Avengers: Secret Wars', '6.720.000 đ', '72 suất chiếu', 'poster-three'], ['Fast & Furious 11', '4.980.000 đ', '56 suất chiếu', 'poster-four'], ['Nhà Gia Tiền', '3.210.000 đ', '40 suất chiếu', 'poster-five']];
const alerts = [['red', 'Suất chiếu “Lật Mặt 7” lúc 19:30 tại Phòng 3 sắp hết vé.', '5 phút trước'], ['blue', 'Doanh thu ngày 02/06/2026 tăng 10.2% so với ngày trước đó.', '30 phút trước'], ['green', 'Phim “Nhà Gia Tiền” sẽ ra mắt vào ngày 07/06/2026.', '2 giờ trước'], ['orange', 'Có 3 yêu cầu đổi/hoàn vé cần xử lý.', '3 giờ trước']];
const sales = [28.5, 32.7, 30.1, 42.8, 38.6, 40.2, 45.2];

export default function App() {
  const [active, setActive] = useState('Tổng quan'); const [expanded, setExpanded] = useState(''); const [open, setOpen] = useState(false); const [noticeOpen, setNoticeOpen] = useState(false); const [period, setPeriod] = useState('Hôm nay');
  return <div className="app-shell"><aside className={`sidebar ${open ? 'open' : ''}`}><div className="sidebar-brand"><div className="logo-image" role="img" aria-label="Aurora Cinema" /><button className="close-sidebar" onClick={() => setOpen(false)}><X /></button></div><div className="system-title"><b>TMS</b><span>Theater Management System</span></div><nav>{nav.map((item) => { const Icon = item.icon; const hasChildren = 'children' in item; const isExpanded = expanded === item.name; return <div className="nav-section" key={item.name}><button className={active === item.name ? 'nav-active' : ''} onClick={() => { setActive(item.name); setExpanded(hasChildren ? (isExpanded ? '' : item.name) : ''); if (!hasChildren) setOpen(false); }}><Icon size={19} /><span>{item.name}</span>{hasChildren && <ChevronDown className={`nav-chevron ${isExpanded ? 'rotated' : ''}`} size={15} />}</button>{hasChildren && isExpanded && <div className="subnav">{item.children.map((child) => <button key={child} className={active === child ? 'sub-active' : ''} onClick={() => { setActive(child); setOpen(false); }}>{child}</button>)}</div>}</div>; })}</nav><div className="admin-card"><div className="admin-avatar">AD</div><div><b>admin</b><span>Quản trị hệ thống</span><small><i /> Online</small></div><ChevronDown size={16} /></div></aside><main className="main-area"><header className="topbar"><button className="open-sidebar" onClick={() => setOpen(true)}><Menu size={23} /></button><div className="topbar-spacer" /><div className="topbar-actions"><div className="notification"><button onClick={() => setNoticeOpen(!noticeOpen)}><Bell size={23} /><b>5</b></button>{noticeOpen && <div className="notification-pop">Bạn có 5 thông báo mới</div>}</div><div className="hello">Xin chào,<strong>Admin</strong></div><ChevronDown size={15} /><div className="user-icon"><UserRound size={22} /></div></div></header><div className="content"><div className="heading"><div><h1>{active === 'Tổng quan' ? 'Tổng quan' : active}</h1><div className="crumb"><span>Trang chủ</span><b>›</b><strong>{active}</strong></div></div><div className="filters"><button><CalendarDays size={17} />03/06/2026</button><button onClick={() => setPeriod(period === 'Hôm nay' ? 'Tuần này' : 'Hôm nay')}>{period}<ChevronDown size={15} /></button></div></div><Stats /><Charts sales={sales} /><Bottom movies={movieData} alerts={alerts} /><footer>© 2026 Aurora Cinema. All rights reserved.<span>Phiên bản 1.0.0</span></footer></div></main></div>;
}
function Stats() { const items = [['blue', Ticket, 'Doanh thu hôm nay', '45.250.000 đ', '+12.5%'], ['green', Receipt, 'Giao dịch hôm nay', '356', '+8.7%'], ['purple', Users, 'Lượt khách hôm nay', '1.248', '+10.3%'], ['orange', Clapperboard, 'Suất chiếu hôm nay', '48', '+4 suất'] ] as const; return <section className="stats-grid">{items.map(([color, Icon, label, value, change]) => <div className="stat-card" key={label}><div className={`stat-icon ${color}`}><Icon size={25} /></div><div><span>{label}</span><strong>{value}</strong><small>{change} <em>so với hôm qua</em></small></div></div>)}</section>; }
function Title({ title, subtitle, action }: { title: string; subtitle?: string; action?: string }) { return <div className="card-title"><div><h2>{title}</h2>{subtitle && <span>{subtitle}</span>}</div>{action && <button>{action}<ChevronDown size={14} /></button>}</div>; }
function Charts({ sales }: { sales: number[] }) { return <section className="charts-grid"><div className="card revenue-card"><Title title="Doanh thu 7 ngày qua" subtitle="(đơn vị: VNĐ)" action="7 ngày qua" /><div className="line-chart"><div className="y-axis"><span>60M</span><span>45M</span><span>30M</span><span>15M</span><span>0</span></div><div className="chart-body"><div className="grid-lines">{[1, 2, 3, 4, 5].map((line) => <i key={line} />)}</div><svg viewBox="0 0 700 180" preserveAspectRatio="none"><path d="M20 130 L130 108 L230 117 L330 73 L430 88 L530 78 L650 64 L650 180 L20 180Z" fill="#2774e926" /><path d="M20 130 L130 108 L230 117 L330 73 L430 88 L530 78 L650 64" fill="none" stroke="#1d6beb" strokeWidth="2.5" /></svg><div className="chart-points">{sales.map((value, index) => <div className="point" style={{ left: `${3 + index * 16.5}%`, top: `${66 - (value - 28) * 3.1}%` }} key={value}><b>{value}M</b><i /><span>{['28/05', '29/05', '30/05', '31/05', '01/06', '02/06', '03/06'][index]}</span></div>)}</div></div></div></div><div className="card channel-card"><Title title="Doanh thu theo kênh bán" /><div className="channel-content"><div className="donut"><strong>45.250.000 đ</strong><span>Tổng doanh thu</span></div><div className="channel-list"><Channel color="blue" label="Quầy vé (POS)" percent="52.1%" value="23.610.000 đ" /><Channel color="green" label="Website/App" percent="36.4%" value="16.480.000 đ" /><Channel color="orange" label="Đối tác (OTA)" percent="11.5%" value="5.160.000 đ" /></div></div></div></section>; }
function Channel({ color, label, percent, value }: { color: string; label: string; percent: string; value: string }) { return <div className="channel-row"><i className={`bullet ${color}`} /><span>{label}</span><strong>{percent}<small>{value}</small></strong></div>; }
function Bottom({ movies, alerts }: { movies: readonly (readonly string[])[]; alerts: readonly (readonly string[])[] }) { return <section className="bottom-grid"><div className="card movie-card"><Title title="Top phim doanh thu cao nhất" /><div className="movie-list">{movies.map((movie, index) => <div className="movie-row" key={movie[0]}><span className="rank">{index + 1}</span><div className={`poster ${movie[3]}`}><Film size={15} /></div><b>{movie[0]}</b><div className="movie-revenue"><strong>{movie[1]}</strong><span>{movie[2]}</span></div></div>)}</div></div><div className="card schedule-card"><Title title="Tình trạng suất chiếu hôm nay" /><div className="schedule-content"><div className="schedule-legend"><Legend color="gray" label="Đã chiếu" value="12" percent="25.0%" /><Legend color="green" label="Đang chiếu" value="8" percent="16.7%" /><Legend color="blue" label="Sắp chiếu" value="14" percent="29.2%" /><Legend color="orange" label="Chưa chiếu" value="14" percent="29.2%" /></div><div className="schedule-donut"><strong>48</strong><span>Tổng suất</span></div></div></div><div className="card notice-card"><Title title="Thông báo" /><div className="notice-list">{alerts.map(([color, text, time]) => <div className="notice-row" key={text}><div className={`notice-icon ${color}`}><FileText size={15} /></div><b>{text}</b><span>{time}</span></div>)}</div></div></section>; }
function Legend({ color, label, value, percent }: { color: string; label: string; value: string; percent: string }) { return <div><i className={`bullet ${color}`} /><span>{label}</span><b>{value}</b><small>{percent}</small></div>; }
