<?php

header('Content-Type: application/json; charset=utf-8');

$host = '127.0.0.1';
$port = 3306;
$username = 'root';
$password = '';

$mysqli = @mysqli_connect($host, $username, $password, '', $port);
if (!$mysqli) {
    echo json_encode(array(
        'success' => false,
        'message' => 'Không thể kết nối MySQL Server trên WAMP: ' . mysqli_connect_error()
    ));
    exit;
}

mysqli_query($mysqli, "SET NAMES utf8");
mysqli_query($mysqli, "CREATE DATABASE IF NOT EXISTS `aurora_db` CHARACTER SET utf8 COLLATE utf8_unicode_ci");
mysqli_select_db($mysqli, 'aurora_db');

$queries = array(
    "CREATE TABLE IF NOT EXISTS `users` ( `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, `username` VARCHAR(60) NOT NULL UNIQUE, `password_hash` VARCHAR(255) NOT NULL, `full_name` VARCHAR(120) NOT NULL, `phone` VARCHAR(20) NULL, `email` VARCHAR(180) NULL, `role` ENUM('super_admin','cinema_admin','supervisor','accounting') NOT NULL DEFAULT 'cinema_admin', `status` ENUM('active','inactive','locked') NOT NULL DEFAULT 'active', `last_login` DATETIME NULL, `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;",
    "CREATE TABLE IF NOT EXISTS `theaters` ( `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, `name` VARCHAR(150) NOT NULL, `address` VARCHAR(255) NULL, `city` VARCHAR(100) NULL, `phone` VARCHAR(20) NULL, `total_screens` INT UNSIGNED NOT NULL DEFAULT 0, `status` ENUM('active','inactive','maintenance') NOT NULL DEFAULT 'active', `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;",
    "CREATE TABLE IF NOT EXISTS `screens` ( `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, `theater_id` BIGINT UNSIGNED NULL, `screen_code` VARCHAR(30) NOT NULL UNIQUE, `name` VARCHAR(100) NOT NULL, `screen_type` ENUM('IMAX','3D_DOLBY_ATMOS','4DX','VIP_STARIUM','STANDARD') NOT NULL DEFAULT 'STANDARD', `total_seats` INT UNSIGNED NOT NULL DEFAULT 120, `projector_status` ENUM('online','standby','maintenance','error') NOT NULL DEFAULT 'online', `sound_system_status` ENUM('online','standby','error') NOT NULL DEFAULT 'online', `hvac_temperature` DECIMAL(4,1) NOT NULL DEFAULT 22.5, `lamp_hours` INT UNSIGNED NOT NULL DEFAULT 0, `status` ENUM('active','paused','cleaning','closed') NOT NULL DEFAULT 'active', `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, KEY `idx_theater_id` (`theater_id`), CONSTRAINT `fk_screens_theater` FOREIGN KEY (`theater_id`) REFERENCES `theaters`(`id`) ON DELETE SET NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;",
    "CREATE TABLE IF NOT EXISTS `movies` ( `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, `title` VARCHAR(200) NOT NULL, `original_title` VARCHAR(200) NULL, `description` TEXT NULL, `plot_details` MEDIUMTEXT NULL, `duration_minutes` INT UNSIGNED NOT NULL DEFAULT 0, `age_rating` VARCHAR(10) NOT NULL DEFAULT 'P', `format` VARCHAR(100) NOT NULL DEFAULT '2D Digital', `genre` VARCHAR(150) NULL, `director` VARCHAR(180) NULL, `cast` TEXT NULL, `writer` VARCHAR(180) NULL, `producer` VARCHAR(180) NULL, `original_language` VARCHAR(80) NULL, `production_country` VARCHAR(100) NULL, `production_year` SMALLINT UNSIGNED NULL, `release_date` DATE NULL, `poster_url` VARCHAR(500) NULL, `trailer_url` VARCHAR(500) NULL, `banner_url` VARCHAR(500) NULL, `status` VARCHAR(40) NOT NULL DEFAULT 'coming_soon', `is_hot` TINYINT(1) NOT NULL DEFAULT 0, `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;",
    "CREATE TABLE IF NOT EXISTS `showtimes` ( `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, `screen_id` BIGINT UNSIGNED NOT NULL, `movie_id` BIGINT UNSIGNED NOT NULL, `show_date` DATE NOT NULL, `start_time` TIME NOT NULL, `end_time` TIME NOT NULL, `booked_seats` INT UNSIGNED NOT NULL DEFAULT 0, `total_seats` INT UNSIGNED NOT NULL DEFAULT 120, `status` ENUM('scheduled','running','finished','cancelled') NOT NULL DEFAULT 'scheduled', `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, KEY `idx_screen_date` (`screen_id`,`show_date`), KEY `idx_movie_date` (`movie_id`,`show_date`), CONSTRAINT `fk_showtimes_screen` FOREIGN KEY (`screen_id`) REFERENCES `screens`(`id`) ON DELETE CASCADE, CONSTRAINT `fk_showtimes_movie` FOREIGN KEY (`movie_id`) REFERENCES `movies`(`id`) ON DELETE CASCADE ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;",
    "CREATE TABLE IF NOT EXISTS `staff_shifts` ( `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, `staff_name` VARCHAR(120) NOT NULL, `position` VARCHAR(80) NOT NULL, `shift_name` VARCHAR(50) NOT NULL, `start_time` TIME NOT NULL, `end_time` TIME NOT NULL, `status` ENUM('on_duty','checked_in','checked_out','absent') NOT NULL DEFAULT 'on_duty', `check_in_at` DATETIME NULL, `check_out_at` DATETIME NULL, `work_date` DATE NOT NULL, `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;",
    "CREATE TABLE IF NOT EXISTS `ticket_types` ( `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, `name` VARCHAR(100) NOT NULL, `code` VARCHAR(40) NOT NULL UNIQUE, `price` DECIMAL(12,2) NOT NULL DEFAULT 0, `description` VARCHAR(255) NULL, `status` ENUM('active','inactive') NOT NULL DEFAULT 'active', `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;",
    "CREATE TABLE IF NOT EXISTS `products` ( `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, `name` VARCHAR(150) NOT NULL, `sku` VARCHAR(50) NOT NULL UNIQUE, `category` VARCHAR(80) NOT NULL DEFAULT 'Concession', `price` DECIMAL(12,2) NOT NULL DEFAULT 0, `stock_quantity` INT UNSIGNED NOT NULL DEFAULT 0, `status` ENUM('active','inactive') NOT NULL DEFAULT 'active', `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;",
    "CREATE TABLE IF NOT EXISTS `vouchers` ( `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, `code` VARCHAR(40) NOT NULL UNIQUE, `name` VARCHAR(150) NOT NULL, `discount_type` ENUM('percent','amount') NOT NULL DEFAULT 'percent', `discount_value` DECIMAL(12,2) NOT NULL DEFAULT 0, `starts_at` DATETIME NOT NULL, `ends_at` DATETIME NOT NULL, `usage_limit` INT UNSIGNED NOT NULL DEFAULT 0, `used_count` INT UNSIGNED NOT NULL DEFAULT 0, `status` ENUM('active','inactive','expired') NOT NULL DEFAULT 'active', `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;",
    "CREATE TABLE IF NOT EXISTS `customers` ( `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, `full_name` VARCHAR(120) NOT NULL, `phone` VARCHAR(20) NOT NULL UNIQUE, `email` VARCHAR(180) NULL, `membership_level` ENUM('standard','silver','gold','platinum') NOT NULL DEFAULT 'standard', `points` INT UNSIGNED NOT NULL DEFAULT 0, `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;",
    "CREATE TABLE IF NOT EXISTS `transactions` ( `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, `transaction_code` VARCHAR(40) NOT NULL UNIQUE, `customer_id` BIGINT UNSIGNED NULL, `channel` ENUM('pos','website','ota') NOT NULL DEFAULT 'pos', `amount` DECIMAL(12,2) NOT NULL DEFAULT 0, `payment_method` VARCHAR(40) NOT NULL DEFAULT 'cash', `status` ENUM('paid','pending','cancelled','refunded') NOT NULL DEFAULT 'paid', `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT `fk_transactions_customer` FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON DELETE SET NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;",
    "CREATE TABLE IF NOT EXISTS `refunds` ( `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, `transaction_id` BIGINT UNSIGNED NOT NULL, `reason` VARCHAR(255) NOT NULL, `amount` DECIMAL(12,2) NOT NULL DEFAULT 0, `status` ENUM('pending','approved','rejected','completed') NOT NULL DEFAULT 'pending', `requested_by` BIGINT UNSIGNED NULL, `processed_at` DATETIME NULL, `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT `fk_refunds_transaction` FOREIGN KEY (`transaction_id`) REFERENCES `transactions`(`id`) ON DELETE CASCADE, CONSTRAINT `fk_refunds_user` FOREIGN KEY (`requested_by`) REFERENCES `users`(`id`) ON DELETE SET NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;",
    "CREATE TABLE IF NOT EXISTS `revenue_logs` ( `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, `log_date` DATE NOT NULL, `ticket_sales` DECIMAL(14,2) NOT NULL DEFAULT 0.00, `concession_sales` DECIMAL(14,2) NOT NULL DEFAULT 0.00, `total_revenue` DECIMAL(14,2) NOT NULL DEFAULT 0.00, `total_tickets` INT UNSIGNED NOT NULL DEFAULT 0, `occupancy_rate` DECIMAL(5,2) NOT NULL DEFAULT 0.00, `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;",
    "CREATE TABLE IF NOT EXISTS `audit_logs` ( `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, `username` VARCHAR(80) NOT NULL, `action` VARCHAR(80) NOT NULL, `details` TEXT NULL, `ip_address` VARCHAR(45) NULL, `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;",
    "CREATE TABLE IF NOT EXISTS `system_configs` ( `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, `config_key` VARCHAR(100) NOT NULL UNIQUE, `config_value` TEXT NULL, `description` VARCHAR(255) NULL, `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;",
    "INSERT INTO `users` (`username`, `password_hash`, `full_name`, `phone`, `email`, `role`, `status`) VALUES ('0328754062', '$2y$12$wZ3cvdry6kOqHV6vdTllB.B9qrFsJLdIZKjofc02GnNletKab1/G2', 'Nguyễn Trần Thái Bảo', '0328754062', 'admin@aurora.vn', 'super_admin', 'active'), ('admin', '$2y$12$wZ3cvdry6kOqHV6vdTllB.B9qrFsJLdIZKjofc02GnNletKab1/G2', 'Nguyễn Trần Thái Bảo', '0328754062', 'admin@aurora.vn', 'cinema_admin', 'active') ON DUPLICATE KEY UPDATE `password_hash` = VALUES(`password_hash`), `full_name` = VALUES(`full_name`), `status` = 'active';",
    "INSERT INTO `theaters` (`name`, `address`, `city`, `phone`, `total_screens`, `status`) VALUES ('Aurora Cinema Thủ Đức', 'Q.Thủ Đức, TP.HCM', 'TP.HCM', '0900000001', 6, 'active') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);",
    "INSERT INTO `screens` (`theater_id`, `screen_code`, `name`, `screen_type`, `total_seats`, `projector_status`, `sound_system_status`, `hvac_temperature`, `lamp_hours`, `status`) VALUES (1, 'SCREEN_01', 'Phòng 01 - Laser IMAX', 'IMAX', 280, 'online', 'online', 22.0, 850, 'active'), (1, 'SCREEN_02', 'Phòng 02 - Dolby Atmos 3D', '3D_DOLBY_ATMOS', 180, 'online', 'online', 22.5, 1240, 'active') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);",
    "INSERT INTO `movies` (`title`, `duration_minutes`, `age_rating`, `format`, `status`, `genre`) VALUES ('Avatar: Dòng Chảy Của Nước', 192, 'T13', '3D IMAX / HFR', 'now_showing', 'Khoa học viễn tưởng'), ('Oppenheimer', 180, 'T18', '2D IMAX 70mm', 'now_showing', 'Tiểu sử / Chính kịch') ON DUPLICATE KEY UPDATE `title` = VALUES(`title`);",
    "INSERT INTO `showtimes` (`screen_id`, `movie_id`, `show_date`, `start_time`, `end_time`, `booked_seats`, `total_seats`, `status`) VALUES (1, 1, CURDATE(), '09:30:00', '12:45:00', 245, 280, 'running'), (2, 2, CURDATE(), '10:00:00', '13:00:00', 165, 180, 'running') ON DUPLICATE KEY UPDATE `status` = VALUES(`status`);",
    "INSERT INTO `ticket_types` (`name`, `code`, `price`, `status`) VALUES ('Người lớn', 'ADULT', 120000, 'active'), ('Học sinh - Sinh viên', 'STUDENT', 90000, 'active'), ('Trẻ em', 'CHILD', 70000, 'active') ON DUPLICATE KEY UPDATE `price` = VALUES(`price`);",
    "INSERT INTO `products` (`name`, `sku`, `category`, `price`, `stock_quantity`, `status`) VALUES ('Bắp rang bơ', 'POPCORN_LARGE', 'Concession', 60000, 200, 'active'), ('Nước ngọt', 'SODA_330', 'Concession', 25000, 300, 'active') ON DUPLICATE KEY UPDATE `price` = VALUES(`price`);",
    "INSERT INTO `vouchers` (`code`, `name`, `discount_type`, `discount_value`, `starts_at`, `ends_at`, `usage_limit`, `status`) VALUES ('AURORA10', 'Giảm 10%', 'percent', 10, NOW(), DATE_ADD(NOW(), INTERVAL 30 DAY), 500, 'active') ON DUPLICATE KEY UPDATE `discount_value` = VALUES(`discount_value`);",
    "INSERT INTO `customers` (`full_name`, `phone`, `email`, `membership_level`, `points`) VALUES ('Khách hàng mẫu', '0900000000', 'customer@aurora.vn', 'silver', 120) ON DUPLICATE KEY UPDATE `points` = VALUES(`points`);",
    "INSERT INTO `transactions` (`transaction_code`, `customer_id`, `channel`, `amount`, `payment_method`, `status`) VALUES ('TXN-001', 1, 'pos', 185000, 'cash', 'paid') ON DUPLICATE KEY UPDATE `amount` = VALUES(`amount`);",
    "INSERT INTO `revenue_logs` (`log_date`, `ticket_sales`, `concession_sales`, `total_revenue`, `total_tickets`, `occupancy_rate`) VALUES (CURDATE(), 185600000.00, 52400000.00, 238000000.00, 1820, 84.50) ON DUPLICATE KEY UPDATE `total_revenue` = VALUES(`total_revenue`);",
    "INSERT INTO `system_configs` (`config_key`, `config_value`, `description`) VALUES ('cinema_name', 'Aurora Cinema', 'Tên rạp'), ('default_currency', 'VND', 'Đơn vị tiền tệ mặc định'), ('booking_close_minutes', '15', 'Thời gian đóng đặt vé trước giờ chiếu') ON DUPLICATE KEY UPDATE `config_value` = VALUES(`config_value`);"
);

foreach ($queries as $sql) {
    if (!mysqli_query($mysqli, $sql)) {
        echo json_encode(array('success' => false, 'message' => 'Lỗi khi tạo bảng hoặc seed dữ liệu: ' . mysqli_error($mysqli), 'sql' => $sql));
        exit;
    }
}

echo json_encode(array(
    'success' => true,
    'message' => 'Cài đặt và khởi tạo schema tối giản aurora_db thành công!',
    'database' => 'aurora_db',
    'tables' => array('users','theaters','screens','movies','showtimes','staff_shifts','ticket_types','products','vouchers','customers','transactions','refunds','revenue_logs','audit_logs','system_configs')
));
