USE `aurora_db`;

CREATE TABLE IF NOT EXISTS `theater_profiles` (
  `theater_id` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  `hero_image_url` VARCHAR(500) NULL,
  `short_description` TEXT NULL,
  `short_description_en` TEXT NULL,
  `description` TEXT NULL,
  `description_en` TEXT NULL,
  `highlights_json` TEXT NULL,
  `highlights_en_json` TEXT NULL,
  `facilities_json` TEXT NULL,
  `facilities_en_json` TEXT NULL,
  `opening_hours` VARCHAR(120) NULL,
  `contact_phone` VARCHAR(30) NULL,
  `map_url` VARCHAR(500) NULL,
  `updated_at` TIMESTAMP NULL,
  CONSTRAINT `fk_theater_profiles_theater` FOREIGN KEY (`theater_id`) REFERENCES `theaters`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Keep the production seed aligned with the seven Aurora locations used by the customer app.
INSERT IGNORE INTO `theaters` (`id`, `name`, `address`, `city`, `created_at`) VALUES
(6, 'Aurora Hà Nội', 'Tầng 6, Vincom Center Bà Triệu, 191 Bà Triệu, Lê Đại Hành, Hai Bà Trưng', 'Hà Nội', NOW()),
(7, 'Aurora Đà Nẵng', 'Tầng 3, Indochina Riverside, 74 Bạch Đằng, Hải Châu 1, Hải Châu', 'Đà Nẵng', NOW());

INSERT IGNORE INTO `screens` (`theater_id`, `name`, `total_seats`) VALUES
(6, 'Phòng 01 - IMAX Laser Ultimate', 260), (6, 'Phòng 02 - Dolby Atmos 4K', 190),
(6, 'Phòng 03 - VIP Gold Class', 60), (6, 'Phòng 04 - Tiêu chuẩn Digital', 150),
(6, 'Phòng 05 - Tiêu chuẩn Digital', 150), (7, 'Phòng 01 - Dolby Atmos 4K', 200),
(7, 'Phòng 02 - VIP Starium Sofa', 55), (7, 'Phòng 03 - 3D Digital', 140),
(7, 'Phòng 04 - Tiêu chuẩn Digital', 130);

INSERT INTO `theater_profiles` (`theater_id`, `hero_image_url`, `short_description`, `short_description_en`, `description`, `description_en`, `highlights_json`, `highlights_en_json`, `facilities_json`, `facilities_en_json`, `opening_hours`, `contact_phone`, `map_url`, `updated_at`) VALUES
(1, 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1600&q=85', 'Cụm rạp trung tâm với trải nghiệm điện ảnh chuẩn quốc tế giữa lòng Quận 1.', 'A central cinema with an international-standard movie experience in the heart of District 1.', 'Aurora Q1 là điểm hẹn điện ảnh flagship của Aurora Cinema tại trung tâm thành phố. Sáu phòng chiếu được đầu tư Laser IMAX, Dolby Atmos và 4DX, cùng sảnh chờ hiện đại để mỗi buổi hẹn phim trở thành một trải nghiệm trọn vẹn.', 'Aurora Q1 is Aurora Cinema''s flagship movie destination in the city centre. Its six auditoriums feature Laser IMAX, Dolby Atmos and 4DX, complemented by a contemporary lobby for a complete movie outing.', '["Laser IMAX", "Dolby Atmos 3D", "4DX Dynamic", "VIP Starium Sofa"]', '["Laser IMAX", "Dolby Atmos 3D", "4DX Dynamic", "VIP Starium Sofa"]', '["Quầy bắp nước", "Wi-Fi miễn phí", "Bãi gửi xe Vincom", "Thanh toán không tiền mặt"]', '["Concession counter", "Free Wi-Fi", "Vincom parking", "Cashless payment"]', '08:30 - 23:30', '1900 2088', 'https://maps.google.com/?q=Vincom+Center+Dong+Khoi', NOW()),
(2, 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=1600&q=85', 'Không gian giải trí năng động cho những buổi hẹn phim và cuối tuần tại Quận 7.', 'An energetic entertainment destination for movie dates and weekends in District 7.', 'Nằm trong SC VivoCity, Aurora Q7 mang đến 5 phòng chiếu với công nghệ Dolby Atmos 4K, 4DX Experience và Gold Class. Vị trí thuận tiện giúp bạn dễ dàng kết hợp mua sắm, ăn uống và thưởng thức bom tấn.', 'Located in SC VivoCity, Aurora Q7 offers five auditoriums with Dolby Atmos 4K, 4DX Experience and Gold Class. Its convenient location makes it easy to combine shopping, dining and a blockbuster.', '["Dolby Atmos 4K", "4DX Experience", "VIP Gold Class", "5 phòng chiếu"]', '["Dolby Atmos 4K", "4DX Experience", "VIP Gold Class", "5 auditoriums"]', '["Khu chờ rộng rãi", "Quầy bắp nước", "Bãi xe TTTM", "Thang máy"]', '["Spacious lounge", "Concession counter", "Mall parking", "Elevators"]', '09:00 - 23:00', '1900 2088', 'https://maps.google.com/?q=SC+VivoCity', NOW()),
(3, 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1600&q=85', 'Trải nghiệm điện ảnh đẳng cấp với tầm nhìn thành phố tại Landmark 81.', 'A premium cinema experience with a city-view setting at Landmark 81.', 'Aurora Landmark 81 là cụm rạp cao cấp dành cho những tín đồ điện ảnh. Hệ thống IMAX 3D Laser Grand, ScreenX 270 độ và Starium Suite đưa bạn vào thế giới phim ảnh sống động, riêng tư và sang trọng.', 'Aurora Landmark 81 is the premium destination for film lovers. IMAX 3D Laser Grand, ScreenX 270° and Starium Suite immerse you in a vivid, private and refined world of cinema.', '["IMAX 3D Laser Grand", "ScreenX 270 độ", "Starium Suite", "300 ghế phòng lớn nhất"]', '["IMAX 3D Laser Grand", "ScreenX 270°", "Starium Suite", "300 seats in the largest auditorium"]', '["Sảnh premium", "Quầy đồ ăn nhanh", "Bãi xe Landmark 81", "Khu vực chờ VIP"]', '["Premium lobby", "Snack counter", "Landmark 81 parking", "VIP waiting area"]', '09:00 - 23:30', '1900 2088', 'https://maps.google.com/?q=Landmark+81', NOW()),
(4, 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1600&q=85', 'Điểm hẹn phim ảnh hiện đại, thuận tiện cho cộng đồng phía Đông thành phố.', 'A modern, convenient movie destination for the city''s eastern community.', 'Tại GigaMall Phạm Văn Đồng, Aurora Thủ Đức phục vụ 4 phòng chiếu với Dolby Atmos 4K và không gian Gold Class. Đây là nơi lý tưởng để cả gia đình, nhóm bạn và sinh viên tận hưởng những bộ phim mới nhất.', 'At GigaMall Pham Van Dong, Aurora Thu Duc offers four auditoriums with Dolby Atmos 4K and Gold Class comfort. It is an ideal outing for families, friends and students to enjoy the newest releases.', '["Dolby Atmos 4K", "Gold Class", "4 phòng chiếu", "Vị trí GigaMall"]', '["Dolby Atmos 4K", "Gold Class", "4 auditoriums", "GigaMall location"]', '["Bãi xe GigaMall", "Khu chờ gia đình", "Quầy bắp nước", "Tiếp cận thang máy"]', '["GigaMall parking", "Family lounge", "Concession counter", "Elevator access"]', '09:00 - 23:00', '1900 2088', 'https://maps.google.com/?q=GigaMall+Thu+Duc', NOW()),
(5, 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1600&q=85', 'Cụm rạp gần sân bay, sẵn sàng cho những lịch hẹn giải trí linh hoạt.', 'A cinema near the airport, ready for flexible entertainment plans.', 'Aurora Tân Bình tại Menas Mall Saigon Airport là lựa chọn tiện lợi cho cư dân khu vực và du khách. Công nghệ Dolby Atmos Surround, phòng VIP Starium cùng lịch chiếu linh hoạt mang đến trải nghiệm thoải mái trước hoặc sau mỗi hành trình.', 'Aurora Tan Binh at Menas Mall Saigon Airport is a convenient choice for local residents and travellers. Dolby Atmos Surround, VIP Starium and flexible showtimes offer a relaxed experience before or after every journey.', '["Dolby Atmos Surround", "VIP Starium", "Gần sân bay", "4 phòng chiếu"]', '["Dolby Atmos Surround", "VIP Starium", "Near the airport", "4 auditoriums"]', '["Bãi xe Menas Mall", "Quầy bắp nước", "Điểm sạc điện thoại", "Thanh toán điện tử"]', '["Menas Mall parking", "Concession counter", "Phone charging points", "Digital payment"]', '09:00 - 23:00', '1900 2088', 'https://maps.google.com/?q=Menas+Mall+Saigon+Airport', NOW()),
(6, 'https://images.unsplash.com/photo-1543536448-d209d2d13a1c?auto=format&fit=crop&w=1600&q=85', 'Không gian điện ảnh hiện đại tại trái tim thủ đô.', 'A modern cinema space in the heart of the capital.', 'Aurora Hà Nội tọa lạc tại Vincom Center Bà Triệu, quy tụ IMAX Laser Ultimate, Dolby Atmos 4K và phòng Gold Class. Từ những suất chiếu gia đình đến các bom tấn định dạng lớn, rạp đáp ứng đa dạng nhu cầu thưởng thức điện ảnh.', 'Aurora Ha Noi is located at Vincom Center Ba Trieu and features IMAX Laser Ultimate, Dolby Atmos 4K and Gold Class. From family screenings to large-format blockbusters, it serves every kind of movie outing.', '["IMAX Laser Ultimate", "Dolby Atmos 4K", "Gold Class", "5 phòng chiếu"]', '["IMAX Laser Ultimate", "Dolby Atmos 4K", "Gold Class", "5 auditoriums"]', '["Bãi xe Vincom", "Sảnh chờ điều hòa", "Quầy bắp nước", "Khu vực hỗ trợ khách hàng"]', '["Vincom parking", "Air-conditioned lounge", "Concession counter", "Guest support desk"]', '08:30 - 23:30', '1900 2088', 'https://maps.google.com/?q=Vincom+Ba+Trieu', NOW()),
(7, 'https://images.unsplash.com/photo-1595769816263-9b910be24d5f?auto=format&fit=crop&w=1600&q=85', 'Điểm hẹn giải trí ven sông dành cho khán giả Đà Nẵng.', 'A riverside entertainment destination for Da Nang audiences.', 'Aurora Đà Nẵng tại Indochina Riverside mang đến không gian xem phim thư thái bên sông Hàn. Hệ thống Dolby Atmos 4K, Starium Sofa và các suất chiếu đa dạng giúp mọi cuộc hẹn trở nên đáng nhớ.', 'Aurora Da Nang at Indochina Riverside provides a relaxed movie experience by the Han River. Dolby Atmos 4K, Starium Sofa and a varied showtime programme make every outing memorable.', '["Dolby Atmos 4K", "VIP Starium Sofa", "Gần sông Hàn", "4 phòng chiếu"]', '["Dolby Atmos 4K", "VIP Starium Sofa", "Near the Han River", "4 auditoriums"]', '["Bãi xe TTTM", "Quầy bắp nước", "Khu chờ hướng sông", "Wi-Fi miễn phí"]', '["Mall parking", "Concession counter", "Riverside waiting area", "Free Wi-Fi"]', '09:00 - 23:00', '1900 2088', 'https://maps.google.com/?q=Indochina+Riverside+Da+Nang', NOW())
ON DUPLICATE KEY UPDATE hero_image_url=VALUES(hero_image_url), short_description=VALUES(short_description), short_description_en=VALUES(short_description_en), description=VALUES(description), description_en=VALUES(description_en), highlights_json=VALUES(highlights_json), highlights_en_json=VALUES(highlights_en_json), facilities_json=VALUES(facilities_json), facilities_en_json=VALUES(facilities_en_json), opening_hours=VALUES(opening_hours), contact_phone=VALUES(contact_phone), map_url=VALUES(map_url), updated_at=VALUES(updated_at);
