import { Armchair, Building2, CalendarDays, ChevronRight, Clock3, Loader2, MapPin, RefreshCw, Ticket } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';

const API_URL = 'http://localhost/AURORA%20CINEMA/customer/backend/public/api.php';
type Props = { movie: any; theaters: any[]; initialTheaterName: string; initialDate: string; onBook: (showtime: any, theater: string) => void };
type ScheduleData = { selectedDate: string; serverTime: string; dates: { date: string }[]; theaters: any[]; showtimes: any[] };

function dayInfo(value: string) { const date = new Date(`${value}T00:00:00+07:00`); return { weekday: new Intl.DateTimeFormat('vi-VN', { weekday: 'short', timeZone: 'Asia/Ho_Chi_Minh' }).format(date), short: new Intl.DateTimeFormat('vi-VN', { day: '2-digit', month: '2-digit', timeZone: 'Asia/Ho_Chi_Minh' }).format(date), full: new Intl.DateTimeFormat('vi-VN', { weekday: 'long', day: '2-digit', month: '2-digit', year: 'numeric', timeZone: 'Asia/Ho_Chi_Minh' }).format(date) }; }
function timeOf(value: string) { return String(value || '').slice(11, 16); }
function period(value: string) { const hour = Number(String(value).slice(11, 13)); return hour < 12 ? 'BUỔI SÁNG' : hour < 18 ? 'BUỔI CHIỀU' : 'BUỔI TỐI'; }

export default function MovieSchedulePanel({ movie, theaters, initialTheaterName, initialDate, onBook }: Props) {
  const initialTheater = theaters.find(item => item.name === initialTheaterName) || theaters[0];
  const [theaterId, setTheaterId] = useState<number | null>(initialTheater?.id || null);
  const [selectedDate, setSelectedDate] = useState(initialDate);
  const [schedule, setSchedule] = useState<ScheduleData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [refreshTick, setRefreshTick] = useState(0);

  useEffect(() => { const timer = window.setInterval(() => setRefreshTick(value => value + 1), 60000); return () => window.clearInterval(timer); }, []);
  useEffect(() => {
    const controller = new AbortController(); setLoading(true); setError('');
    fetch(`${API_URL}?action=movie_schedule&movie_id=${movie.id}&date=${selectedDate}&_=${Date.now()}`, { credentials: 'include', cache: 'no-store', signal: controller.signal })
      .then(async response => { const result = await response.json(); if (!response.ok) throw new Error(result.message); return result; })
      .then((result: ScheduleData) => { setSchedule(result); setTheaterId(current => { const available = result.theaters.find(item => item.id === current && item.showtimeCount > 0); if (available) return current; const preferred = result.theaters.find(item => item.name === initialTheaterName && item.showtimeCount > 0); const firstActive = result.theaters.find(item => item.showtimeCount > 0); return preferred?.id || firstActive?.id || result.theaters[0]?.id || null; }); })
      .catch(err => { if (err.name !== 'AbortError') setError(err.message || 'Không thể tải lịch chiếu.'); })
      .finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [movie.id, selectedDate, refreshTick, initialTheaterName]);

  const scheduleTheaters = schedule?.theaters || theaters;
  const selectedTheater = scheduleTheaters.find(item => item.id === theaterId);
  const currentShowtimes = useMemo(() => (schedule?.showtimes || []).filter(item => item.theater_id === theaterId), [schedule, theaterId]);
  const groups = useMemo(() => { const values: Record<string, any[]> = {}; currentShowtimes.forEach(item => { const key = period(item.starts_at); if (!values[key]) values[key] = []; values[key].push(item); }); return values; }, [currentShowtimes]);
  function record(eventType: string, selectedTheaterId: number, showtimeId = 0) { fetch(`${API_URL}?action=schedule_event`, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ movieId: movie.id, theaterId: selectedTheaterId, showtimeId, date: selectedDate, eventType }) }).catch(() => {}); }
  function chooseTheater(item: any) { setTheaterId(item.id); record('SELECT_THEATER', item.id); }
  function chooseShowtime(item: any) { if (item.availability === 'SOLD_OUT') return; record('SELECT_SHOWTIME', item.theater_id, item.id); onBook(item, selectedTheater?.name || initialTheaterName); }

  return <section className="md-schedule">
    <style>{`
      .md-schedule{background:#fff;border-radius:20px;margin-top:20px;box-shadow:0 12px 36px rgba(13,27,46,.08);border:1px solid #e3eaf2;overflow:hidden}.md-schedule-head{padding:22px 24px;background:linear-gradient(115deg,#0b2039,#173b61);color:#fff}.md-date-row{display:grid;grid-template-columns:repeat(7,1fr);gap:8px;margin-top:18px}.md-date{border:1px solid rgba(255,255,255,.22);background:rgba(255,255,255,.07);color:#dce8f3;border-radius:11px;padding:9px 5px;cursor:pointer}.md-date.active{background:#f4c04a;border-color:#f4c04a;color:#0d1b2e;box-shadow:0 6px 18px rgba(244,192,74,.25)}.md-theaters{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;padding:18px 22px;background:#f7f9fc;border-bottom:1px solid #e4ebf2}.md-theater{display:flex;text-align:left;align-items:center;gap:10px;border:1px solid #d9e3ed;background:#fff;border-radius:12px;padding:11px;cursor:pointer;color:#37516b;min-width:0}.md-theater.active{border-color:#dca01d;background:#fff9e9;box-shadow:0 0 0 2px rgba(244,192,74,.18)}.md-theater:disabled{opacity:.52;cursor:not-allowed}.md-show-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:11px}.md-show{position:relative;text-align:left;border:1px solid #dce5ee;background:#fff;border-radius:13px;padding:14px;cursor:pointer;transition:.18s ease;overflow:hidden}.md-show:hover{transform:translateY(-2px);border-color:#e0a526;box-shadow:0 9px 20px rgba(20,48,79,.1)}.md-show:disabled{cursor:not-allowed;opacity:.58;transform:none}.md-seat-bar{height:3px;border-radius:9px;background:#e8eef4;overflow:hidden;margin-top:10px}.md-seat-bar span{display:block;height:100%;background:#22a66a}.md-empty{padding:38px;text-align:center;border:1px dashed #d6e0e9;border-radius:14px;background:#fafbfd;color:#71869a}.spin{animation:md-spin .8s linear infinite}@keyframes md-spin{to{transform:rotate(360deg)}}@media(max-width:820px){.md-theaters{grid-template-columns:repeat(2,minmax(0,1fr))}.md-show-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:580px){.md-schedule-head{padding:18px 14px}.md-date-row{display:flex;overflow-x:auto}.md-date{min-width:66px}.md-theaters{grid-template-columns:1fr;padding:13px}.md-show-grid{grid-template-columns:1fr}}
    `}</style>
    <div className="md-schedule-head">
      <div style={{ display: 'flex', justifyContent: 'space-between', gap: 14, alignItems: 'flex-start', flexWrap: 'wrap' }}><div><div style={{ display: 'flex', alignItems: 'center', gap: 8, color: '#f4c04a', fontSize: 11, fontWeight: 900, letterSpacing: .8 }}><CalendarDays size={16} /> LỊCH CHIẾU THEO CỤM RẠP</div><h2 style={{ margin: '7px 0 3px', fontSize: 21 }}>Chọn rạp và suất chiếu phù hợp</h2><div style={{ color: '#b9ccde', fontSize: 11.5 }}>Tình trạng ghế được cập nhật tự động mỗi phút</div></div><div style={{ display: 'flex', alignItems: 'center', gap: 6, color: '#b9ccde', fontSize: 10.5 }}><RefreshCw size={12} className={loading ? 'spin' : ''} /> {schedule?.serverTime ? `Cập nhật ${timeOf(schedule.serverTime)}` : 'Đang đồng bộ'}</div></div>
      <div className="md-date-row">{(schedule?.dates || [{ date: initialDate }]).map(item => { const info = dayInfo(item.date); return <button key={item.date} className={`md-date${item.date === selectedDate ? ' active' : ''}`} onClick={() => setSelectedDate(item.date)}><div style={{ fontSize: 9.5, fontWeight: 800, textTransform: 'uppercase' }}>{info.weekday}</div><div style={{ fontSize: 13, fontWeight: 900, marginTop: 2 }}>{info.short}</div></button>; })}</div>
    </div>
    <div className="md-theaters">{scheduleTheaters.map(item => <button key={item.id} className={`md-theater${theaterId === item.id ? ' active' : ''}`} disabled={item.showtimeCount === 0} onClick={() => chooseTheater(item)}><span style={{ width: 34, height: 34, borderRadius: 10, background: theaterId === item.id ? '#0d2744' : '#eef3f8', display: 'flex', alignItems: 'center', justifyContent: 'center', color: theaterId === item.id ? '#f4c04a' : '#55718c', flexShrink: 0 }}><MapPin size={16} /></span><span style={{ minWidth: 0, flex: 1 }}><strong style={{ display: 'block', color: theaterId === item.id ? '#132d49' : '#3d566f', fontSize: 12, overflow: 'hidden', whiteSpace: 'nowrap', textOverflow: 'ellipsis' }}>{item.name}</strong><small style={{ display: 'block', marginTop: 3, color: item.showtimeCount ? '#178454' : '#94a3b8', fontSize: 9.5, fontWeight: 700 }}>{item.showtimeCount ? `${item.showtimeCount} suất đang mở` : 'Chưa có suất'}</small></span></button>)}</div>
    <div style={{ padding: '20px 22px 24px' }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12, marginBottom: 18, flexWrap: 'wrap' }}><div><div style={{ display: 'flex', alignItems: 'center', gap: 7, color: '#102842', fontWeight: 900, fontSize: 15 }}><Building2 size={17} color="#d99b15" />{selectedTheater?.name || initialTheaterName}</div><div style={{ marginTop: 4, color: '#7b8fa3', fontSize: 10.5 }}>{selectedTheater?.address || 'Địa chỉ rạp đang được cập nhật'}</div></div><div style={{ color: '#60758b', fontSize: 11, padding: '7px 10px', borderRadius: 8, background: '#f3f6f9' }}>{dayInfo(selectedDate).full}</div></div>
      {loading ? <div className="md-empty"><Loader2 className="spin" size={22} style={{ marginBottom: 8 }} /><div>Đang tải suất chiếu và tình trạng ghế...</div></div> : error ? <div className="md-empty" style={{ color: '#b42318' }}>{error}</div> : currentShowtimes.length ? Object.keys(groups).map(group => <div key={group} style={{ marginBottom: 20 }}><div style={{ display: 'flex', alignItems: 'center', gap: 7, marginBottom: 9, color: '#647b91', fontSize: 10, fontWeight: 900, letterSpacing: .6 }}><Clock3 size={13} /> {group}</div><div className="md-show-grid">{groups[group].map(item => { const soldOut = item.availability === 'SOLD_OUT'; const limited = item.availability === 'LIMITED'; const availablePercent = Math.max(0, 100 - Number(item.occupancy_percent || 0)); return <button key={item.id} className="md-show" disabled={soldOut} onClick={() => chooseShowtime(item)}><div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 }}><div><div style={{ color: '#102842', fontSize: 20, fontWeight: 900 }}>{timeOf(item.starts_at)}</div><div style={{ marginTop: 2, color: '#8a9bad', fontSize: 9.5 }}>{timeOf(item.starts_at)} – {timeOf(item.ends_at)}</div></div><span style={{ padding: '4px 7px', borderRadius: 99, background: soldOut ? '#f1f5f9' : limited ? '#fff1f2' : '#ecfdf3', color: soldOut ? '#64748b' : limited ? '#c0223e' : '#168354', fontSize: 8.5, fontWeight: 900 }}>{soldOut ? 'HẾT GHẾ' : limited ? `CÒN ${item.seats_left} GHẾ` : 'CÒN GHẾ'}</span></div><div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 12 }}><span style={{ display: 'flex', alignItems: 'center', gap: 5, color: '#62798f', fontSize: 10.5 }}><Armchair size={13} /> {item.screen_name}</span></div><div className="md-seat-bar"><span style={{ width: `${availablePercent}%`, background: limited ? '#e99430' : soldOut ? '#cbd5e1' : '#22a66a' }} /></div><div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 5, color: '#8b9cad', fontSize: 8.5 }}><span>{item.seats_left}/{item.total_seats} ghế trống</span><span style={{ display: 'flex', alignItems: 'center', gap: 2, color: '#bd8210', fontWeight: 800 }}>CHỌN SUẤT <ChevronRight size={11} /></span></div></button>; })}</div></div>) : <div className="md-empty"><Ticket size={26} color="#9aabba" style={{ marginBottom: 9 }} /><div style={{ color: '#3f5871', fontWeight: 800 }}>Chưa có suất chiếu phù hợp</div><div style={{ marginTop: 4, fontSize: 11 }}>Vui lòng chọn ngày hoặc cụm rạp khác.</div></div>}
    </div>
  </section>;
}
